config/routes.rb
Rails.application.routes.draw do
 
  resources :categories
  resources :tasks
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'sessions#new'
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :task_categories
  has_many :tasks, through: :task_categories 

validates :name, presence: true, length: { maximum: 30 }
validates_uniqueness_of :name 
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many :task_categories
  has_many :categories, through: :task_categories 
  validates :title, presence: true, length: {maximum: 100 }
  validates :description, presence: true, length: {maximum: 300 }
end

app/models/task_category.rb
class TaskCategory < ApplicationRecord
  belongs_to :task
  belongs_to :category
  end 

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks
  validates :username, presence: true, 
  uniqueness: { case_sensitive: false }, 
  length: { minimum: 3, maximum: 25 }
VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
validates :email, presence: true, 
  uniqueness: { case_sensitive: false }, 
  length: { maximum: 105 },
  format: { with: VALID_EMAIL_REGEX }
has_secure_password
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end

  

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  
  def show
  end

  
  def new
    @category = Category.new
  end

  def edit
  end


  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:notice] ='Category was successfully created.'
      redirect_to @category 
    else
      render :new
    end
  end

  
  def update
    if @category.update(category_params)
      flash[:notice] =' Category was successfully updated.'
      redirect_to @category
    else
      render :edit
    end

  end
  def destroy
    @category.destroy
    flash[:notice] ='Category was successfully deleted'
    redirect_to categories_url
  end

  private
    
    def set_category
      @category = Category.find(params[:id])
    end

    
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def start
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to tasks_path if logged_in?
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully"
      redirect_to tasks_path
    else
      flash.now[:alert] = "There was something wrong with your login details"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :require_user

  # GET /tasks
  def index
    @tasks = current_user.tasks
  end

  # GET /tasks/1
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  def create
    @task = Task.new(task_params)
    
    @task.user = current_user
    if @task.save
      redirect_to @task, notice: 'Task was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /tasks/1
  def update
    if @task.update(task_params)
      redirect_to @task, notice: 'Task was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tasks/1
  def destroy
    @task.destroy
    redirect_to tasks_url, notice: 'Task was successfully deleted.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:title, :description, category_ids: [] )
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  

  def show
    @tasks = @user.tasks

  end

  def new
    @user = User.new
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your account information was successfully updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to the GOALS #{@user.username}, you have successfully signed up"
      redirect_to login_path
    else
      render 'new'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account and all associated articles successfully deleted"
    redirect_to tasks_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_category.html.erb
<%= link_to category.name, categories_path%> 

app/views/categories/_form.html.erb
<div class="new_task_whole">
  <%= form_with(model: @category,class:'new_task_form') do |form| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% @category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="newt_field">
    <%= form.label :name, class:'newt_title'%>
    <%= form.text_field :name, class:'newt_input'%>
  </div>  

  



  <div class="actions">
    <%=form.submit(class:'newt_btn')%>
    <br>
  </div>
  <%= link_to 'Back', tasks_path ,class:"newt_back" %>

<% end %>

</div>
</div>

app/views/categories/edit.html.erb
<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>



<div class='feed-whole'>
<%= link_to 'Add Category', new_category_path ,class:"newt_button"%>


  <div class = "feed-table-container">

    
      <% @categories.each do |category| %>

      <div class=feed-card>
      <div class="card-header"><%= category.name %></div>
      <div class="card-body">


        </div>
    
        <div class="actions1"> 
        <%= link_to 'See more |', category ,class:"acts"%>
        <%= link_to 'Edit |', edit_category_path(category), class:"acts" %>
        <%= link_to 'Delete', category, method: :delete, data: { confirm: 'Are you sure?' }, class:"acts"  %>
      </div>
      </div>

  
      <% end %>

    

    </div>

  </div>

</div>

#----------------------------------------------------------------------


<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<%= render 'form'%>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

  <div class="show_whole">
    <div class="show_container">
    <div class="show_content">
    <div class="show_title">
      
      <%= @category.name %>
    </div>
    <div class = "show_description">

    <div class="show_body"> 
      
      
    </div>
    </div>

    <div class="actions1 show_actions">
    <%= link_to 'Edit |', edit_category_path(@category),class:"acts" %> 
    <%= link_to 'Back', categories_path ,class:"acts"%>
    </div>
    </div>
    </div>
    </div>

app/views/layouts/_navbar.html.erb
  <% if logged_in? %>
<style>
@import url('https://fonts.googleapis.com/css2?family=Permanent+Marker&family=Shadows+Into+Light&display=swap');
</style>
<nav class = "start-up-nav">
<div class="nav_cont">
  <h1 class= "nav_title">G O A L S</h1>
  <div class="mid-cont">
  <%= link_to "Categories", categories_path ,class:'nav_contents'%> 
  <%= link_to "Task", tasks_path,class:'nav_contents' %> 
  </div>
</div>
  
   <div class="lgt-container">
    <%= link_to "Log out",logout_path, class: "lgt_btn", method: :delete %>
 </div>

</nav>

  <% end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProductivityApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if logged_in? %>
      <%= render 'layouts/navbar' %>  
      <% end%>
    <%= yield %>
  </body>
</html>

app/views/pages/start.html.erb
<style>
@import url('https://fonts.googleapis.com/css2?family=Permanent+Marker&family=Shadows+Into+Light&display=swap');
</style>

<nav class = "start-up-nav">
<h1 class= "nav_title">G O A L S</h1>
<div class = "log_in_container">
<p>Email <input> </p>
<p>Password <input> </p>
<button class = "log_in_btn">Log in </button>
 </div>

</nav>


<div class = "mega-container">


  <div class="content-container">
  
    
 
    <div class = "punch-line-container">
    <p class="quote">LOSERS LET  IT HAPPEN; WINNERS MAKE IT HAPPEN! <%= link_to "Sign Up!", signup_path %></p>
    
    </div>
  </div>



</div>

app/views/tasks/_form.html.erb
<div class="new_task_whole">

<div class="new_task_container">
<%= form_with(model: task,class:'new_task_form') do |form| %>
  <h1>Update</h1>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="newt_field">
    <%= form.label :title, class:'newt_title'%>
    <%= form.text_field :title, class:'newt_input'%>
  </div>  

  <div class="newt_field">
    <%= form.label :description , class:'newt_label_description' %>
    <%= form.text_area :description, class:'newt_ta'%>
  </div>

<div class="newt_field">
<%= form.label :category,'Categories' %>
<%= form.collection_select(:category, Category.all, :id, :name,
{prompt: "Select categories below:"}, { multiple: true, size: 3 }) %> 
</div>

  <div class="actions">
    <%=form.submit(class:'newt_btn')%>
    <br>
  </div>
  <%= link_to 'Back', tasks_path ,class:"newt_back" %>

<% end %>

</div>
</div>

app/views/tasks/edit.html.erb
<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<style>
@import url('https://fonts.googleapis.com/css2?family=Permanent+Marker&family=Shadows+Into+Light&display=swap');
</style>
<p id="notice"><%= notice %></p>
<div class='feed-whole'>
<%= link_to 'New Task', new_task_path ,class:"newt_button"%>


  <div class = "feed-table-container">

    
      <% @tasks.each do |task| %>

      <div class=feed-card>
      <div class="card-header"><%= task.user.username %></div>
      <div class="card-body">
        <h5 class="card-title"><%= task.title %></h5>
        <%=render task.categories if task.categories.any? %>
        <p class="card-text">
          <%= task.description %>
        </p>
        </div>
    
        <div class="actions1"> 
        <%= link_to 'See more |', task ,class:"acts"%>
        <%= link_to 'Edit |', edit_task_path(task),class:"acts" %>
        <%= link_to 'Delete', task, method: :delete, data: { confirm: 'Are you sure?' }, class:"acts"  %>
      </div>
      </div>

  
      <% end %>

    

    </div>

  </div>

</div>

app/views/tasks/new.html.erb
<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>
    <div class="show_whole">
    <div class="show_container">
    <div class="show_content">
    <div class="show_title">
      Title:
      <%= @task.title %>
    </div>
    <div class = "show_description">

    <div class="show_body"> 
      <%= @task.description %>
      
    </div>
    </div>

    <div class="actions1 show_actions">
    <%= link_to 'Edit |', edit_task_path(@task),class:"acts" %> 
    <%= link_to 'Back', tasks_path ,class:"acts"%>
    </div>
    </div>
    </div>
    </div>

app/views/users/_form.html.erb
 
 <div class ="sgnup_whl">

 <div class="sign_up_container">
 <%= form_with(model: @user, class:'sgnup_form') do |form| %>
 <h1>Sign Up !</h1>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>

      <ul>
        <% @user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="sgnup_field">

   <div class="sgnup_div">
      <%= form.label :username %>
      <%= form.text_field :username, class:'sgnup_input' %>
   </div>
  
   <div class="sgnup_div">
      <%= form.label :email %>
      <%= form.email_field :email, class:'sgnup_input' %>
   </div>
   <div class="sgnup_div">
     <%= form.label :password %>
     <%= form.text_field :password, class:'sgnup_input'%>
    </div>
  </div>

  <div class="actions">
    <%= form.submit "SIGN UP" ,class:'sgnup_final_btn' %>
  </div>


<% end %>
</div>
</div>

app/views/users/new.html.erb
#sign up
<%= render "form"%>